:- include('linhaA1.pl').
:- include('linhaA2.pl').
:- include('linhaA3.pl').
:- include('linhaA4.pl').
:- include('linhaA5.pl').
:- include('linhaA6.pl').
:- include('linhaB1.pl').
:- include('linhaB2.pl').
:- include('linhaB3.pl').
:- include('linhaB4.pl').
:- include('linhaC1.pl').
:- include('linhaC2.pl').
:- include('linhaC3.pl').
:- include('linhaC4.pl').
:- include('linhaC5.pl').
:- include('linhaC6.pl').
:- include('linhaD1.pl').
:- include('linhaD2.pl').
:- include('linhaE1.pl').
:- include('linhaE2.pl').
:- include('linha1.pl').
:- include('linha2.pl').
:- include('linha3.pl').
:- include('linha3bis.pl').
:- include('linha4.pl').
:- include('linha5.pl').
:- include('linha6.pl').
:- include('linha7.pl').
:- include('linha7bis.pl').
:- include('linha8.pl').
:- include('linha9.pl').
:- include('linha10.pl').
:- include('linha11.pl').
:- include('linha12.pl').
:- include('linha13.1.pl').
:- include('linha13.2.pl').
:- include('linha14.pl').